---
- hosts: kube_control_plane  
  become: true
  tasks:
    - name: "kubectl apply calico"
      become: true
      shell: "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico-typha.yaml"    

    - name: "Storing Join Command"
      shell: "kubeadm token create --print-join-command > {{ ssh_home_dir }}/{{ token_execute_file  }}"


- hosts: kube_node  
  become: true
  remote_user: "{{ ssh_user }}"
  tasks:
    - name: "Copying files to remote server"    
      copy:
        src: "{{ ssh_home_dir }}/{{ token_execute_file }}"
        dest: "{{ ssh_home_dir }}/{{ token_execute_file }}"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0755"

    - name: "Joining Worker Nodes iwth Kubernetes master"      
      shell: 
        cmd: "{{ ssh_home_dir }}/{{ token_execute_file }}"

    - name: "Clearing Token File"
      file:
        path: "{{ ssh_home_dir }}/{{ token_execute_file }}"
        state: "absent"
        
