---
- hosts: kube_control_plane  
  become: true
  tasks:
    - name: "kubectl apply calico"
      become: true
      become_method: sudo
      become_user: "{{ ssh_user }}"
      shell: "kubectl create -f {{ calico_manifests_url }}"
    
    - name: "Storing Join Command"
      shell: "kubeadm token create --print-join-command > {{ ssh_home_dir }}/{{ token_execute_file  }}"


- hosts: kube_node  
  become: true
  remote_user: "{{ ssh_user }}"
  tasks:
    - name: "Copying files to remote server"    
      copy:
        src: "{{ ssh_home_dir }}/{{ token_execute_file }}"
        dest: "{{ ssh_home_dir }}/{{ token_execute_file }}"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0755"

    - name: "Joining Worker Nodes iwth Kubernetes master"      
      become: true
      become_user: "{{ ssh_user }}"
      become_method: sudo
      shell:
        cmd: "{{ ssh_home_dir }}/{{ token_execute_file }}"

    - name: "Clearing Token File"
      file:
        path: "{{ ssh_home_dir }}/{{ token_execute_file }}"
        state: "absent"
        
